run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0.0
  dupl:
    threshold: 100
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  gocognit:
    min-complexity: 10
  nestif:
    min-complexity: 4
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
    - performance
    - diagnostic
    - style
    - opinionated
    disabled-tags:
    - experimental
  godot:
    scope: all
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/gocatchup/gocatchup
  gosimple:
    go: "1.16"
  govet:
    check-shadowing: true
    enable-all: true
  nakedret:
    max-func-lines: 1
  staticcheck:
    go: "1.16"
  unused:
    go: "1.16"
  revive:
    confidence: 0.0
    enableAllRules: true

linters:
  presets:
  - bugs
  - unused
  - style
  - error
  - performance
  - complexity
  - comment
  - import
  - format
  - metalinter
  disable:
  - misspell
  - golint
  - maligned
  - interfacer
  - scopelint

issues:
  exclude-use-default: false
  max-same-issues: 50
