name: go

on:
  push:
    tags:
    - v*
    branches:
    - master
    - main
  pull_request:
    branches:
    - main
    paths:
    - '**.go'
    - .github/workflows/go.yml

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: go build 
      run: make all-build
    - name: Archive gocatcup binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin/**
        retention-days: 7
